apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ghcr.io/lyyppppp/ci-cd-demo:5105d3caefb938a0e56f4b3edcb4ceb33694eea6
        ports:
        - containerPort: 3000
---

